name: reusable workflow
on: workflow_call
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
         - name: output information
           run: |
            echo "The reusable workflow has been called"